[package]
name = "multi-lsp"
version = "0.1.0"
edition = "2021"
description = "An LSP Proxy to multiple language servers"
license = "MIT"
repository = "https://github.com/voidKandy/multi-lsp.git"
readme = "README.md"


[dependencies]
async-stream = "0.3.3"
clap = { version = "4.1.1", features = ["derive"] }
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full"] }
tokio-stream = "0.1.11"
toml_edit = { version = "0.17.1", features = ["easy", "serde"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
